import type { Metadata } from "next";
import { Exo, Geist } from "next/font/google";
import "./globals.css";
import NavBarTop from "./_components/NavBar/NavBarTop";
import NavBarBottom from "./_components/NavBar/NavBarBottom";
import { cn } from "@/lib/utils";
import TopFooter from "./_components/Footer/TopFooter";
import Footer from "./_components/Footer/Footer";
import { Toaster } from "@/components/ui/sonner";
import MySessionProvider from "./_providers/MySessionProvider";
import CartContextProvider from "./_contexts/CartContextProvider";
import WhishlistContextProvider from "./_contexts/WhishlistContextProvider";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const exo = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        exo.className,
        "font-sans",
        geist.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <MySessionProvider>
          <CartContextProvider>
            <WhishlistContextProvider>
            <NavBarTop />
            <NavBarBottom />
            {children}
            <Toaster />
            <TopFooter />
            <Footer />
            </WhishlistContextProvider>
          </CartContextProvider>
        </MySessionProvider>
      </body>
    </html>
  );
}
